@echo off
echo Compiling LaTeX project...
echo Running pdflatex (1/3)...
pdflatex -interaction=nonstopmode main24x16
echo Running bibtex...
bibtex main24x16
echo Running pdflatex (2/3)...
pdflatex -interaction=nonstopmode main24x16
echo Running pdflatex (3/3)...
pdflatex -interaction=nonstopmode main24x16
echo Compilation complete.
pause
